apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: credit-scoring-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"  # или yandex-ingress-controller, если установлен
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: credit-scoring-service
            port:
              number: 80